name = "fabricmodpack-ender"
author = "Violet Scarelli"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e992a393bf96a34f3fed4e37b51ad8312eec0e299828cbba97e4fb819504133"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.19.2", "1.19.1"]
