name = "fabricmodpack-ender"
author = "Violet Scarelli"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2b4e6bf553dbde89bd4c92b96f833e7c05e7640e6ffdf8b3d4915bc507208b3"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.19.2", "1.19.1"]
